name = "phoneproxy"
compatibility_date = "2022-08-13"
account_id = "e4e117e43dcd195f5ab2207218d22932"
main = "index.js"


# wrangler secret put ACCOUNT_SID: your twilio account SID
# wrangler secret put AUTH_TOKEN: your twilio auth token
# wrangler secret put TWILIO_NUM: your twilio phone number
